sudo: required
language: c
services:
  - docker
before_install:
  - docker pull bitcraze/builder
script:
  # Build cf2 basic
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2

  # Build cf2 with "all" features enabled
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2 DEBUG=1 "EXTRA_CFLAGS=-DCALIBRATED_LED_MORSE -DIMU_TAKE_ACCEL_BIAS -DIMU_MPU6500_DLPF_256HZ -DMADWICK_QUATERNION_IMU -DDEBUG_QUEUE_MONITOR -DENABLE_BQ_DECK -DSITAW_ENABLED -DOW_WRITE_TEST -DOW_READ_TEST -DDEBUG_PRINT_ON_UART -DENABLE_UART1 -DENABLE_UART2"

  # Build cf2 with bosch sensors
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2 SENSORS=bosch

  # Build cf2 with TDMA
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2 DEBUG=1 LPS_TDMA_ENABLE=1 "EXTRA_CFLAGS=-DTDMA_NSLOTS_BITS=1 -DTDMA_SLOT=0"

  # Build cf2 with TDOA2 positioning mode
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2 DEBUG=1 LPS_TDOA_ENABLE=1

  # Build cf2 with TDOA3 positioning mode
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2 DEBUG=1 LPS_TDOA3_ENABLE=1

  # Build cf2 with TDOA3 and all config options
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2 DEBUG=1 LPS_TDOA3_ENABLE=1 "EXTRA_CFLAGS=-DLPS_2D_POSITION_HEIGHT=1.2 -DLPS_LONGER_RANGE"

  # Build the tag platform
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=tag

  # Build with the lighthouse driver
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/make clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=cf2 "EXTRA_CFLAGS=-DDISABLE_LIGHTHOUSE_DRIVER=0"
